### ISSUE TITLE
Cannot install v. 0.2.5, 0.2.6 and 0.2.7 with "pip"

### ISSUE THREAD

**Issue by csbubbles** [mhogg/pyoctree#30]
I am having this problem trying to install it with `pip`.

It can see that **0.2.7** was released:

```bash
$ pip search pyoctree

pyoctree (0.2.7)  - Octree structure containing 3D triangular mesh model
```

However, it cannot install it:

```bash
$ pip install pyoctree==0.2.7

Collecting pyoctree==0.2.7
  Could not find a version that satisfies the requirement pyoctree==0.2.7 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.2.4)
No matching distribution found for pyoctree==0.2.7
```

The verbose mode says that the released version is incompatible with the Python version I am using (getting the same error when using Python 2.7 and 3.6). Check the last lines of the log below ("**it is not compatible with this Python**" message at the end of lines for versions `2.5`, `2.6` and `2.7`):

```bash
$ pip install pyoctree==0.2.7 -vvv

Created temporary directory: /private/var/folders/r9/d3kkplcx0gn76g_4kyrspy4w0000gn/T/pip-ephem-wheel-cache-AOCGpb
Created temporary directory: /private/var/folders/r9/d3kkplcx0gn76g_4kyrspy4w0000gn/T/pip-req-tracker-kIpsQj
Created requirements tracker '/private/var/folders/r9/d3kkplcx0gn76g_4kyrspy4w0000gn/T/pip-req-tracker-kIpsQj'
Created temporary directory: /private/var/folders/r9/d3kkplcx0gn76g_4kyrspy4w0000gn/T/pip-install-aL8kY4
Collecting pyoctree==0.2.7
  1 location(s) to search for versions of pyoctree:
  * https://pypi.org/simple/pyoctree/
  Getting page https://pypi.org/simple/pyoctree/
  Looking up "https://pypi.org/simple/pyoctree/" in the cache
  Current age based on date: 178
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 178
  Analyzing links from page https://pypi.org/simple/pyoctree/
    Found link https://files.pythonhosted.org/packages/34/1a/1225e4219a9692699b62c6a014142c678c38ab766fb7c9e421e9d5b22e02/pyoctree-0.1.0.zip#sha256=c93d219bb62708227d3cd18bfae45ab62437fbe04fdaf9968a5c1793dedb27e3 (from https://pypi.org/simple/pyoctree/), version: 0.1.0
    Found link https://files.pythonhosted.org/packages/b8/6b/bc3b71e3a852b6bd30b80489daf0a17a28e16806071bb92f6053cbf1035d/pyoctree-0.1.1.zip#sha256=e1eced7f53561c08de4d0fefc48b755737006cfcb98ed2c3bcd3014b9defdc05 (from https://pypi.org/simple/pyoctree/), version: 0.1.1
    Skipping link 

...

    Found link https://files.pythonhosted.org/packages/62/cf/cde6b411521b51523b60b91f3da28bccb8a47e0253e061c8679ba9bec666/pyoctree-0.2.2.tar.gz#sha256=f5ab9727fd40d37609306bedfbb78600709fb70a003cb7a8cd83fddbcbfe40d6 (from https://pypi.org/simple/pyoctree/), version: 0.2.2
    Skipping link https://files.pythonhosted.org/packages/b8/81/74a13e0b94a6bf38b8d8bf1a49d34ee1940892044d5c30df3676f2aebb75/pyoctree-0.2.4-cp27-cp27m-win_amd64.whl#sha256=36a029f5462ce44ac47746c91e09844a55dc01fde8af5e27b6232792c4cec37f (from https://pypi.org/simple/pyoctree/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/db/8d/8f3f0303796674e6d3536b7cc91675de0d4c618e5bb141125c7da008eadd/pyoctree-0.2.4-cp36-cp36m-win_amd64.whl#sha256=a1702d13adfe8a6bcabea02f6e6278c320437ecc8cd1055cd7d771af7ae51f70 (from https://pypi.org/simple/pyoctree/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/94/d2/848f4fbaae1a5262029238bccf8130cd3ffd1bed62a19f219adc023a95ee/pyoctree-0.2.4.tar.gz#sha256=703b8b9123df81b4866a458f359711b6a5015b02b2d018fbf57d3ec445b3a12d (from https://pypi.org/simple/pyoctree/), version: 0.2.4
    Skipping link https://files.pythonhosted.org/packages/20/00/446362e635b78013957ac72bce631ad2a1369300324c001494a258554383/pyoctree-0.2.5-cp36-cp36m-win_amd64.whl#sha256=36fb9364438032ddc7dd941739325ff7e9da8227bfc36fe579fb43f94bd35b83 (from https://pypi.org/simple/pyoctree/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/c2/25/053008a768ea66ec5c6d5612214d2ddc4b38436656e5d8a3423cb3e0cbc2/pyoctree-0.2.6-cp36-cp36m-win_amd64.whl#sha256=6a9f7857cb3f31b27c56d328884e96f428a1dde126bbb7716e83401de87781ae (from https://pypi.org/simple/pyoctree/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/f0/05/23b51083020def64e2aea7f88122e7d30bdbfbd0b691d213ba699d2b834b/pyoctree-0.2.7-cp36-cp36m-win_amd64.whl#sha256=ef5d82c19a0f0c8bcb029a97111b095bc292d43763f1eaac5b146f412ed981cc (from https://pypi.org/simple/pyoctree/); it is not compatible with this Python
```

Ran with Python `2.7.10` and `3.6.3` with the same outcome. `pip`'s version is `18.0`.

**Comment by csbubbles** [comment]
I tried to install `wheel` files from this page:
https://github.com/mhogg/pyoctree/releases

It didn't work either:

```bash
$ python --version
Python 3.6.5

$ pip install https://github.com/mhogg/pyoctree/releases/download/v0.2.7/pyoctree-0.2.7-cp36-cp36m-win_amd64.whl
pyoctree-0.2.7-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```

PS macOS v. 10.13.6.

**Comment by csbubbles** [comment]
BTW, it looks like `.zip` and/or `.tar.gz` files don't exist for those versions in the pip repo:
https://pypi.org/simple/pyoctree/

<img width="300" alt="screen shot 2018-08-13 at 11 02 04 pm" src="https://user-images.githubusercontent.com/56697/44074305-ec907f0a-9f4c-11e8-86fc-38bc67b99661.png">

But for the versions that have `zip`/`tar` distribution packages, pip can successfully find them:

```bash
$ pip search pyoctree
pyoctree (0.2.7)  - Octree structure containing 3D triangular mesh model

$ pip install pyoctree==0.2.7
Collecting pyoctree==0.2.7
  Could not find a version that satisfies the requirement pyoctree==0.2.7
  (from versions: 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.2.4)
No matching distribution found for pyoctree==0.2.7
```

So, I wonder if this is a problem of packaging and providing `zip`/`tar` along with `.whl` could fix the issue.

**Comment by mhogg** [comment]
Good catch - you are probably right. I will upload the source files.

**Comment by mhogg** [comment]
I have created a new version 0.2.8 to try to fix this. I have uploaded both the source and the wheel to PyPi. Please see if this works for you.
-Michael

**Comment by mhogg** [comment]
Looking at PyPi, all the classifer information has not been read from the setup file correctly. This is the mostly likely cause, as pip will not know relevant system and version information. Looks like something has changed with the new PyPi website that my scripts no longer work. Will have to look into this.

**Comment by csbubbles** [comment]
I think the issue with loading and installing `pyoctree` seems to be resolved with `0.2.8`. At least I am not getting that "incompatibility" error anymore. But it turns out the issue with `numpy` is still not fixes:

```bash
$ pip install pyoctree==0.2.8

Collecting pyoctree==0.2.8
  Using cached https://files.pythonhosted.org/packages/d7/75/f1e951abb7163d8aa0cb4112c5c0bbce789c695b2efcd6e53ac0ca26332d/pyoctree-0.2.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kp/d191cq5j33g5s3nyvmzlx6q00000gn/T/pip-install-th_vce5u/pyoctree/setup.py", line 11, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/kp/d191cq5j33g5s3nyvmzlx6q00000gn/T/pip-install-th_vce5u/pyoctree/
```

But I think I might know one possible solution there, I am going to update the other ticket.

**Comment by mhogg** [comment]
Fixed in release v0.2.10
